### ISSUE TITLE
Client.getTokenChallenge triggers UncaughtException

### ISSUE THREAD

**Issue by kenshyx** [textileio/js-textile#1209]
This happens when the callback promise is rejected https://github.com/textileio/js-textile/blob/649303c63430721d8a8e42c02620353c484e90bc/packages/client/src/index.ts#L327.

**Comment by kenshyx** [comment]
The easiest solution it would be to wrap it with a `try{} catch(e){}` and reject the [promise](https://github.com/textileio/js-textile/blob/649303c63430721d8a8e42c02620353c484e90bc/packages/client/src/index.ts#L322) with the error that was caught.

**Comment by kenshyx** [comment]
Any thoughts on this @carsonfarmer ?

**Comment by carsonfarmer** [comment]
Ah good catch (haha). Yes your suggestion looks reasonable, I'll try to get a PR up to fix this ASAP, might not be for a day or two though.
