### ISSUE TITLE
Error calling document.save() more than once in ^0.2.1

### ISSUE THREAD

**Issue by kwingram25** [textileio/js-textile#1217]
Encountering a breaking error when I attempt to call save() on any document type more than once per page load. Refreshing the page resets it. This is only happening in 0.2.1 and higher. Appears to be trying to add the schema more than once?
![Screenshot from 2022-02-18 16-41-11](https://user-images.githubusercontent.com/879755/154771072-3e067bc0-9e99-4cb7-8009-51ba23282dde.png)

**Comment by carsonfarmer** [comment]
Thanks for this report @kwingram25. I’m travelling at the moment, but will dig into this ASAP.

**Comment by carsonfarmer** [comment]
Ah ok, looking at the source and the diff from 0.2.0 -> 0.2.1, it looks like the schema validator is now "stateful" when it should not be.

**Comment by carsonfarmer** [comment]
Fixed with #1218 and now available as `@textile/threaddb@0.2.3`
