### ISSUE TITLE
Documentation for Context

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-textile#140]
Stealing some nice explanatory ideas from @andrewxhill 👍 

> Context [...] allows you to shift what role you are using to hit the APIs. This is interesting because your app can use an API as you, the developer, with all your capabilities. or as Users of your app, which are sandboxed but can create threads/buckets of their own in that sandbox.

**Comment by andrewxhill** [comment]
Still getting my head around the context idea. What are the total possible contexts that a developer would use? 

contexts, under the hood, seem to be tracking some configuration of headers necessary to do the thing the developer is attempting. 

Here's my guess, but maybe this is where I'm missing something.

1. User API Context == you are doing things with the 'user key'
2. Account API Context == you are doing things with the 'account key'

I know there is something lower level if you do things like create keys (which happens in your test) but that isn't a developer concern in this library afaik. 

I might also be missing the cases that there needs to be some different context for buckets versus normal threads, etc., so hopefully this question is helpful for documenting.

**Comment by carsonfarmer** [comment]
Fixed with https://github.com/textileio/docs/pull/138
