### ISSUE TITLE
port 

### ISSUE THREAD

**Issue by oznfc** [textileio/js-textile#142]
grpc-web-client.umd.js:1 WebSocket connection to 'ws://127.0.0.1:6007/api.pb.API/NewStore' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by carsonfarmer** [comment]
Hi @oznfc, thanks for the report. Can you help us by providing a little additional information? What library are you using @textile/textile, @textile/threads-client, etc? And are you running it against a local `threadsd` daemon? Perhaps you could point us to where you are getting the example from?

**Comment by oznfc** [comment]
ı want to start js-exampless/todo-app.  when I start app I have this error. How can ı start.  Use textileio/go-threads

**Comment by carsonfarmer** [comment]
Ok, thanks for this. At the moment, that example is not working. We're working to update the examples to the latest APIs and libraries. Please bear with us, it should be ready again early next week.

**Comment by carsonfarmer** [comment]
Closing this as 'outdated' and in favor of more specific issues on the various examples in js-examples, where work to address this issue is ongoing.
