### ISSUE TITLE
Two small issues with 'hub login'

### ISSUE THREAD

**Issue by tjayrush** [textileio/js-textile#326]
Two small issues related to `hub login`:

1. Your system sends an email when I `hub login.` The email was taking a minute or two to arrive, but when I clicked the link in the email, Hub would say:

	> Error! Gateway Timeout: HTTP status code 504; transport: received the unexpected content-type "text/html"

   This happened three times. Perhaps you could extend the timeout period?

2. I entered an incorrect email and got this message:

	> We sent an email to the account address. Please follow the steps provided inside it.
	> Error! User not found

   Perhaps you should check the account exists before reporting that an email was sent. Not a big deal, but every detail matters in the user interface.

**Comment by andrewxhill** [comment]
Cool, thanks! I opened a new ticket for your second point over on the repo where accounts are managed. 

for the first part, we were planning this https://github.com/textileio/textile/issues/206 which is just to let you still use the link of the first email by resuming.

**Comment by carsonfarmer** [comment]
Can we close this one here in favor of the other two tickets in textile/textile?

**Comment by tjayrush** [comment]
If you wish...
