### ISSUE TITLE
Sparate Thread auth and Hub pinning permission

### ISSUE THREAD

**Issue by Jewcub** [textileio/js-textile#371]
To lower complexity and calls to an app creator's server, we should separate the auth flow from the Hub specific processes. 

There would be no need to send a request to the server on every refresh just to add the `user_group_keys`. instead, the first time the DB is created, the app server could use its `user_group_keys` to register that this ThreadDB is one that will be pinned under his/her account.

Advantages: the user's keys are usually accessed client-side, therefore the repeated calls to keep the Client connected could be done straight from the client. This eliminates the need for the 'token' used now. It simplifies and standardizes the auth flow because the auth will look exactly the same whether you are using the hub to pin/replicate or not. The initial registration call could be also now done with REST calls, eliminating the need for the extra complexity with the websockets back and forth. The registration call could also be a convenient place to create settings for the DB like maximum size to keep pinned.

client.withUserAuth could remain the same as now, with the key signing challenge, but the userAuth object would need to be simplified. It should really just be the public key and signature.

The hub would need a new method or API endpoint, something accepting a request like:

```js
threadRegistration: {
    thread_ID: 'asdfa124124efaf...',
    user_group_key: '1234asdfr1...',
    user_group_secret: '1jk234j...',
    max_size: 1000 // In Megabytes
}
```

**Comment by carsonfarmer** [comment]
Closing this with "this is already the case", the thread and buckets "auth" flow (getToken, getTokenChallenge) is separate from the userAuth flows and calls, though there are convenience static methods that allow you to do both at once. This separation is being made even more explicit in https://github.com/textileio/js-threaddb, so any further discussion can happen there.
