### ISSUE TITLE
Update size to MB

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-textile#595]
https://github.com/textileio/js-hub/blob/a62eb930868b2f3f7621a98f485663e142eb524f/packages/buckets/src/api/index.ts#L456

**Comment by carsonfarmer** [comment]
Do we still need to do this, given we don't expose this as an option? Should we expose this "chunking" size as an option?

**Comment by carsonfarmer** [comment]
Closing this one as "stale".
