### ISSUE TITLE
Question: what DBs does `Client.listThreads` list?

### ISSUE THREAD

**Issue by Schwartz10** [textileio/js-textile#713]
Sorry if this isn't the best place to ask a less-urgent question (let me know where is) - what DBs does `Client.listThreads` list? Is it just the ones that this identity created? Created and opened (joined?). Trying to figure out the best way to list all my databases (including those I've been invited to).

**Comment by carsonfarmer** [comment]
It should list all databases to which this identity has access

**Comment by Schwartz10** [comment]
How do you define "has access"?

**Comment by carsonfarmer** [comment]
Has created, or has been invited to.

**Comment by carsonfarmer** [comment]
Closing as "answered", but also, see this (https://github.com/textileio/textile/issues/447) ticket for some clarification around what is being listed here.
