### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Schwartz10** [textileio/js-textile#714]
```
../../node_modules/@textile/threads-id/dist/index.d.ts:102:21 - error TS2749: 'Name' refers to a value, but is being used as a type here. Did you mean 'typeof Name'?

102     toString(base?: Name): string;
```

I have trouble compiling my typescript project after installing the `@textile/hub` repo into my project. Although, it works fine in a different project? Not sure if I have to have a specific tsconfig setting enabled / disabled for this to work properly?

**Comment by carsonfarmer** [comment]
Hmmm, do you have a global `Name` object in your project somewhere that is a value?

**Comment by Schwartz10** [comment]
No global objects, no. When I step inside the file, it gives me the same error too:

![image](https://user-images.githubusercontent.com/12353734/100134876-dc1ec000-2e56-11eb-9fbb-9a34147a777c.png)

It doesn't look like Name from multibase is getting picked up? 
![image](https://user-images.githubusercontent.com/12353734/100134914-e93baf00-2e56-11eb-9d52-7b8f0ac2ca35.png)

**Comment by carsonfarmer** [comment]
Ah ok, hmmm. I think we need to lock down out multi base version. Can you tell me which version you have in the project that _is_ working vs the one that _isn't_ working?

**Comment by Schwartz10** [comment]
Odd because both are using `multibase@3.1.0` (which I see (after a brief skim) has no `name` export)? This is in a lerna repository and I have many packages that lean on multibase:

```
    "/@ceramicnetwork/docid",
    "/@ceramicnetwork/key-did-resolver",
    "/@textile/crypto",
    "/cid-tool",
    "/cids",
    "/ipfs-cli",
    "/ipfs-core",
    "/ipfs-http-client",
    "/ipfs-http-gateway",
    "/ipfs-http-server",
    "/ipfs-repo",
    "/ipfs-repo-migrations",
    "/ipns",
    "/is-ipfs",
    "/libp2p-crypto",
    "/libp2p-floodsub/libp2p-interfaces",
    "/libp2p-gossipsub/libp2p-interfaces",
    "/libp2p-interfaces",
    "/libp2p/libp2p-interfaces",
    "/multiaddr",
    "/multicodec/uint8arrays",
    "/multihashes",
    "/uint8arrays"
```

Only difference here is that the one that works is a node server, and the one that doesn't is an npm package that we publish

**Comment by carsonfarmer** [comment]
Ok, well I'm just going to create a PR to make this type less strict. Should be an easy fix. In the mean time, just modify your local version to accept "any" there?
