### ISSUE TITLE
Uncaught ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by jshuo** [textileio/js-textile#741]
TextDecoder is only supported in browser mode... @textile/security@0.4.0 added the dependencies of TextDecoder/Encoder, and  it is causing issues of 'Uncaught ReferenceError: TextDecoder is not defined' when running nodejs console mode for testing

**Comment by carsonfarmer** [comment]
Which version of Nodejs are you running? It should be there as early as v8.3.0? If not, a polyfill can be included. We can look into including it automatically.

**Comment by carsonfarmer** [comment]
This is a good option for now: https://github.com/anonyco/FastestSmallestTextEncoderDecoder
