### ISSUE TITLE
Bucket pushPath on Safari does not support Blob object

### ISSUE THREAD

**Issue by kenshyx** [textileio/js-textile#948]
The `pushPath` api from `Buckets` throws an error on Safari(desktop and mobile) if the `content` is a Blob object. It works as expected on FF and Chrome.
![Screenshot 2021-02-23 at 18 44 27](https://user-images.githubusercontent.com/3396463/108884758-3de1f800-7607-11eb-9075-40d6ab01a435.png)

**Comment by kenshyx** [comment]
Hey @carsonfarmer , any updates on this? ;/ I still can't use bucket `pushPath` from Safari.

**Comment by kenshyx** [comment]
Additional error log when I'm trying to use bucket `listPath` from Safari
```
[Error] WebSocket connection to 'wss://webapi.hub.textile.io/api.bucketsd.pb.APIService/List' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 100 - Protocol error)
```

**Comment by carsonfarmer** [comment]
This latest error is likely just a temporary connection issue. The latter error is more troubling. I've seen something like this before. Where are you blobs coming from?

**Comment by carsonfarmer** [comment]
Are you able to share some reproducible example?

**Comment by kenshyx** [comment]
The protocol error is not temporary, this is not working for months now(Monterey update), another example: 
![Screenshot 2022-02-03 at 13 33 42](https://user-images.githubusercontent.com/3396463/152343850-65bdd571-5966-4c49-9268-63b0c438251f.png)
 Here is an explanation of this error https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache/

```typescript
// example for kNWErrorDomainPOSIX error 100 - Protocol error
const hubUser = Users.withUserAuth(...userAuth);
await hubUser.getToken(...identity);
await hubUser.setupMailbox();
const mailboxID = await hubUser.getMailboxID();
hubUser.watchInbox(mailboxID, ev => {});

```

**Comment by carsonfarmer** [comment]
Ok, I'm going to cc @sanderpick on this one, as he might have some insight into the nginx issues?

**Comment by sanderpick** [comment]
@kenshyx apologies for the delay! this one fell through the cracks. do you by chance have a site/app that i can visit in safari to see this error?

**Comment by kenshyx** [comment]
@sanderpick you can test the functionality here https://akasha.ethereum.world/ but you will have to sign up in order to be able to post content(ex: images), I will send you an invitation code on discord.

**Comment by sanderpick** [comment]
thanks for invite codes. i created one account from Brave with an eth address and another in safari with email. i was able to add images from both browsers... the console image below is from safari showing the `PushPath` call. let me know what else i should try in order to reproduce this.

<img width="1025" alt="Screen Shot 2022-02-25 at 2 06 52 PM" src="https://user-images.githubusercontent.com/361000/155809662-edde8a38-c321-410e-9903-712e7f4a337c.png">
<img width="729" alt="Screen Shot 2022-02-25 at 2 06 27 PM" src="https://user-images.githubusercontent.com/361000/155809668-79e7190d-32fc-4261-a42e-0d2da621f1e3.png">
<img width="1379" alt="Screen Shot 2022-02-25 at 2 04 59 PM" src="https://user-images.githubusercontent.com/361000/155809673-7e938c2a-0bdf-4597-92c9-d79233dfcdb7.png">

**Comment by kenshyx** [comment]
this is what I get when I'm trying to upload anything from Safari
![Screenshot 2022-02-26 at 12 56 29](https://user-images.githubusercontent.com/3396463/155842287-c1bc1e05-6a3d-4cda-97d0-3c32d014c547.png)
![Screenshot 2022-02-26 at 12 59 40](https://user-images.githubusercontent.com/3396463/155842369-29afcdc4-ccff-4378-8777-98efacc90cbd.png)

`Safari Version 15.3 (17612.4.9.1.8)`

**Comment by kenshyx** [comment]
I've found the issue, after the release of v15 of Safari it seems like it enables an experimental feature by default `NSURLSession Websocket`, if I disable it everything works fine. You can find this feature at `Open Safari -> Develop -> Experimental Features -> NSURLSession Websocket`.

**Comment by kenshyx** [comment]
This is the issue https://github.com/improbable-eng/grpc-web/pull/1061 that affects textile.

**Comment by carsonfarmer** [comment]
Oh wow, this is awesome @kenshyx! Thanks for digging in there. @sanderpick let me know if I can help with getting this "fix" integrated?

**Comment by sanderpick** [comment]
hey this is great. i can blast out the update in a couple hours.

**Comment by kenshyx** [comment]
It's working now! 🎉

**Comment by kenshyx** [comment]
Fixed in https://github.com/textileio/textile/commit/b25c8562e139cd76b494d9dc5ee5f6634fb7304d

**Comment by carsonfarmer** [comment]
Huzzah!
